### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by akhmadarief** [sayyidyofa/nwa-gis-laravel#5]
- Error when saving new GIS entry on fullscreen
- Edit Geometry Data doesn't show
- Error when Edit Wilderness Data
- Error when delete gis index

**Comment by sayyidyofa** [comment]
> * Error when saving new GIS entry on fullscreen
> * Edit Geometry Data doesn't show
> * Error when Edit Wilderness Data
> * Error when delete gis index

Edit Geometry Data doesn't show is assigned to @akhmadarief , any updates will be placed in this issue
